# Generated by Django 4.0.3 on 2022-03-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="catalog.language"),
        ),
    ]
