# Generated by Django 4.0.3 on 2022-03-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={"ordering": ["due_back"], "permissions": (("can_mark_returned", "Set book as returned"),)},
        ),
    ]
